language: csharp
dotnet : 3.0.100
mono : none

script:
  - apt update&& apt -y install apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common
  - wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
  - add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ 
  - apt update&&apt -y install build-essential
  - echo "install Java"
  - apt -y install adoptopenjdk-8-hotspot
  - echo "buld C"
  - cd /root/project/LargestRectangleInBinaryMatrixC && gcc -std=c90 -pedantic -g -rdynamic Source.c -o run
  - echo "build Java"
  - java -version && cd /root/project/LargestRectangleInBinaryMatrixJava/src/com/company && javac Main.java
  - cd /root/project && dotnet restore&& dotnet build&& dotnet test TestLargestRectangleInBinaryMatrix/TestLargestRectangleInBinaryMatrix.csproj
 