version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run:
          name: install
          command : apt update&& apt -y install apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common&&wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -&&add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ &&apt update&&apt -y install build-essential
      
      - run:
          name: installJava
          command : apt -y install adoptopenjdk-8-hotspot
      - run:
          name: buildC
          command : cd /root/project/LargestRectangleInBinaryMatrixC && gcc -std=c90 -pedantic -g -rdynamic Source.c -o run
      - run:
          name: buildJava
          command : java -version && cd /root/project/LargestRectangleInBinaryMatrixJava/src/com/company && javac Main.java
      - run:
          name: test
          command : cd /root/project && dotnet restore&& dotnet build&& dotnet test TestLargestRectangleInBinaryMatrix/TestLargestRectangleInBinaryMatrix.csproj