version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run:
          name: dotnet
		  command : apt update && apt install openjdk-8-jdk && apt install python3.6
          command: dotnet restore	
          command : dotnet build
          command : dotnet test TestLargestRectangleInBinaryMatrix/TestLargestRectangleInBinaryMatrix.csproj	