version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run:
          name: installJava
          command :apt update&& apt install apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common&&wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -&&add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ &&apt update&&apt install adoptopenjdk-8-hotspot
      
      - run:
          name: install
          command : apt install python3.6
      - run:
          name: dotnet
          command : dotnet restore&& dotnet build&& dotnet test TestLargestRectangleInBinaryMatrix/TestLargestRectangleInBinaryMatrix.csproj