version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: dotnet
          command : dotnet restore
          command : dotnet build
          command : dotnet test TestLargestRectangleInBinaryMatrix/TestLargestRectangleInBinaryMatrix.csproj